drop_outliers:
  carat: 
    min: 0
    max: 3
  depth:
    min: 55
    max: 70
  table:
    min: 50
    max: 70
  price:
    min: null
    max: null
  x:
    min: 3
    max: 9
  y:
    min: 3
    max: 10
  z:
    min: 2
    max: 6

preprocessors:
  target: "price"
  PF_degree: 3
  PF_interaction: false
  scalers: minmax

split:
  target: "price"
  seed: 42
  split_ratio: 0.2

train:
  target: "price"
  weights: distance
  n_neighbors: 8

evaluate:
  target: "price"
